set nocompatible                " choose no compatibility with legacy vi
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#begin()

"let Vundle manage Vundle
Plugin 'gmarik/vundle'
    
" github Bundles here:
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/nerdcommenter' 
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-ragtag'
Plugin 'tpope/vim-cucumber'
Plugin 'sudar/vim-arduino-syntax'
Plugin 'vim-ruby/vim-ruby'
Plugin 'taglist.vim'

call vundle#end()

filetype plugin indent on       " load file type plugins + indentation
syntax on
set showcmd                     " display incomplete commands
set encoding=utf-8
set fileencoding=utf-8
set showmatch                   " show the matching (){} [] etc

"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set nobackup
set vb t_vb=
set number

"" let me use the mouse when I want to
set mouse=a

let mapleader = ","

map Q :q!
map <F1> :bn<CR>
map <C-J> :wa<CR>
imap <C-J> <ESC>:wa<CR>
map <leader>j :wa<CR>

:colorscheme desert 

" Make it easy to update/reload .vimrc
nmap <leader>s :source ~/.vimrc<CR>

" bind control-l to hashrocket
imap <C-l> <Space>=><Space>

" open buffers to choose from
map <C-o> :buffers<CR>

nmap <leader>n :tabnext<CR>
nmap <leader>b :tabprev<CR>
nmap <leader>r :!!<CR>

" switch between split windows
nmap <leader>w <c-w><c-w>

" for the command t plugin
nmap <leader>t :CtrlP<CR>

" add .ctrlp to a dir and it will not search up for the base of the repo
" but will search from the current dir only
let g:ctrlp_root_markers = ['.ctrlp']

set wildignore+=.git,*.class,**/classes/**,**/CVS/**,**/vendor/**
let NERDTreeIgnore=['\~$', 'CVS', '.git', '.bundle']

autocmd FileType make set noexpandtab
autocmd FileType python set noexpandtab
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype haml setlocal ts=2 sts=2 sw=2
autocmd Filetype sass setlocal ts=2 sts=2 sw=2
autocmd Filetype story setlocal ts=2 sts=2 sw=2
autocmd Filetype groovy setlocal ts=2 sts=2 sw=2

" copy and paste stuff
set clipboard=unnamed


" double percentage sign in command mode is expanded
" to directory of current file - http://vimcasts.org/e/14
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" switch between last two buffers
nnoremap <leader><leader> <c-^>

" always show hidden files in the nerdy tree
" NERD related things
let NERDTreeShowHidden=1
set wildignore+=.git,*.class,**/classes/**,**/CVS/**
let NERDTreeIgnore=['\~$', 'CVS', '\.swp$']
nmap <leader>d :NERDTreeToggle<CR>
nmap <silent> <F7> :NERDTreeToggle<CR>
nmap <leader>f :NERDTreeFind<CR>

" Cucumber Vim
nmap <leader>c [<C-d>

" OS X only but ones I really like to have

" open tabs with command-number
map <D-1> :tabn 1<CR>
map <D-2> :tabn 2<CR>
map <D-3> :tabn 3<CR>
map <D-4> :tabn 4<CR>
map <D-5> :tabn 5<CR>
map <D-6> :tabn 6<CR>
map <D-7> :tabn 7<CR>
map <D-8> :tabn 8<CR>
map <D-9> :tabn 9<CR>

