set nocompatible                " choose no compatibility with legacy vi
syntax enable
set encoding=utf-8
set fileencoding=utf-8
set showcmd                     " display incomplete commands
filetype plugin indent on       " load file type plugins + indentation

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

"let Vundle manage Vundle
Bundle 'gmarik/vundle'
    
" github Bundles here:
Bundle 'tpope/vim-fugitive'
Bundle 'scrooloose/nerdtree'
Bundle 'FredKSchott/CoVim'
Bundle 'kien/ctrlp.vim'


"" Whitespace
set nowrap                      " don't wrap lines
set tabstop=2 shiftwidth=2      " a tab is two spaces (or set this to 4)
set expandtab                   " use spaces, not tabs (optional)
set backspace=indent,eol,start  " backspace through everything in insert mode

"" Searching
set hlsearch                    " highlight matches
set incsearch                   " incremental searching
set ignorecase                  " searches are case insensitive...
set smartcase                   " ... unless they contain at least one capital letter

set nobackup
set vb t_vb=
set number

"" let me use the mouse when I want to
set mouse=a

let mapleader = ","

map Q :q!
map <F1> :bn<CR>
map <C-A> :wa<CR>
imap <C-A> <ESC>:wa<CR>
map <leader>a :wa<CR>

:colorscheme desert 

nmap <leader>d :NERDTreeToggle<CR>
nmap <silent> <F7> :NERDTreeToggle<CR>

" Make it easy to update/reload .vimrc
nmap <leader>s :source ~/.vimrc<CR>

" bind control-l to hashrocket
imap <C-l> <Space>=><Space>

" open tabs with command-number
map <D-1> :tabn 1<CR>
map <D-2> :tabn 2<CR>
map <D-3> :tabn 3<CR>
map <D-4> :tabn 4<CR>
map <D-5> :tabn 5<CR>
map <D-6> :tabn 6<CR>
map <D-7> :tabn 7<CR>
map <D-8> :tabn 8<CR>
map <D-9> :tabn 9<CR>

nmap <leader>n :tabnext<CR>
nmap <leader>b :tabprev<CR>
nmap <leader>r :!!<CR>

" switch between split windows
nmap <leader>w <c-w><c-w>


" for the command t plugin
nmap <leader>t :CtrlP<CR>

set wildignore+=.git,*.class,**/classes/**,**/CVS/**
let NERDTreeIgnore=['\~$', 'CVS']


autocmd FileType make set noexpandtab
autocmd FileType python set noexpandtab
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype haml setlocal ts=2 sts=2 sw=2
autocmd Filetype sass setlocal ts=2 sts=2 sw=2
autocmd Filetype story setlocal ts=2 sts=2 sw=2
autocmd Filetype groovy setlocal ts=2 sts=2 sw=2


" double percentage sign in command mode is expanded
" to directory of current file - http://vimcasts.org/e/14
cnoremap %% <C-R>=expand('%:h').'/'<cr>

" switch between last two buffers
nnoremap <leader><leader> <c-^>

" always show hidden files in the nerdy tree
let NERDTreeShowHidden=1
